packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@supabase/ssr": ^0.5.1
  "@supabase/supabase-js": ^2.46.1
  "drizzle-orm": 0.36.0
  "postgres": 3.4.5
  "@figma/plugin-typings": ^1.99.0
  "@figma/widget-typings": ^1.9.1
  "@trpc/client": 11.0.0-rc.482
  "@trpc/react-query": 11.0.0-rc.482
  "@trpc/server": 11.0.0-rc.482
  "@types/node": ^22.7.8
  "@types/react-dom": npm:types-react-dom@19.0.0-rc.1
  "@types/react": npm:types-react@19.0.0-rc.1
  "@vitejs/plugin-react": ^4.3.3
  "design-tokens-format-module": ^0.10.1
  "eslint-config-next": ^14.2.6
  concurrently: ^8.2.2
  esbuild: ^0.23.1
  eslint: ^8.57.0
  next: ^15.0.2
  postcss: ^8.4.39
  prettier: ^3.3.3
  react-dom: 19.0.0-rc-02c0e824-20241028
  react-hook-form: ^7.53.1
  react: 19.0.0-rc-02c0e824-20241028
  tailwindcss: ^3.4.7
  typescript: 5.5.4
  vite-plugin-singlefile: ^2.0.3
  vite: ^5.4.10
  zod: ^3.23.8
