packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  typescript: ^5.5.4
  prettier: ^3.3.3
  eslint: ^8.57.0
  vite: ^5.3.1
  react: ^18.3.1
  react-dom: ^18.3.1
  "@types/react": ^18.3.3
  "@types/react-dom": ^18.3.0
  "style-dictionary": ^4.0.1
  "@vitejs/plugin-react": ^4.3.1
  "@trpc/server": ^10.45.2
  zod: ^3.23.8

