packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@figma/plugin-typings": ^1.98.0
  "@trpc/client": 11.0.0-rc.482
  "@trpc/react-query": 11.0.0-rc.482
  "@trpc/server": 11.0.0-rc.482
  "@types/node": ^22.4.1
  "@types/react-dom": ^18.3.0
  "@types/react": ^18.3.3
  "@vitejs/plugin-react": ^4.3.1
  "style-dictionary": ^4.0.1
  eslint: ^8.57.0
  next: ^14.2.5
  postcss: ^8.4.39
  prettier: ^3.3.3
  react-dom: ^18.3.1
  react: ^18.3.1
  tailwindcss: ^3.4.7
  typescript: ^5.5.4
  vite: ^5.3.1
  zod: ^3.23.8
