name: 💾 Migrate DB

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  migrate-db:
    name: Migrate DB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tools/github/setup

      - name: Install Dependencies
        run: pnpm install

      - name: Run Drizzle Migration
        working-directory: apps/dashboard
        run: pnpm db:migrate
        env: # Or as an environment variable
          DATABASE_URL: ${{ secrets.POSTGRES_URL }}
